### ISSUE TITLE
USER STORY: Create Sign-Up Page

### ISSUE THREAD

**Issue by Exochos** [SeattleColleges/nsc-events-nextjs#117]
As a developer, I would like to have a functional sign-up page modified to fit the web app's (NSC Events) theme.
[ ]. There should be a “Confirm Password” text field
[ ]. Add North Seattle college logo.
[ ]. The name text field should be replaced with a “First Name” text field and “Last Name” text field
~~[ ]. Implement ability to signUp~~
[ ]. Both password fields should have the ability to be toggled (shown and hidden)
[ ]. Text in fields should be visible (at the moment, the text is white)
[ ]. Remove the “Already have an account?” text and the “Log In” button

**Comment by taylorpapke** [comment]
Hey @Exochos, I think we should leave "implement ability to signUp" to be part of a user story for sprint 2 since it will probably require an additional 2 issues (1 for the front and 1 for the back). I think this user story is big enough with all the UI features alone and especially now that we are down to 1 week left for sprint 1.
