### ISSUE TITLE
Event Details Page: Add edit , delete, archive, and attend buttons (UI only)

### ISSUE THREAD

**Issue by Ali-7s** [SeattleColleges/nsc-events-nextjs#207]

**Comment by heosman** [comment]
@Ali-7s An update to this issue is that we should add text labels for the edit, delete and archive buttons, for ease of use for the user.

Here's an updated visual:
<img width="1106" alt="Event Detail page visual" src="https://github.com/SeattleColleges/nsc-events-nextjs/assets/77591083/fe6dca30-98c1-4cbc-b37c-72076d0601b0">
